### ISSUE TITLE
Foreman 1.21+ Support

### ISSUE THREAD

**Issue by metalcated** [dm-drogeriemarkt/foreman_rescue#16]
I have Foreman 1.21.x and experienced issues loading this plugin. 

`rake aborted!
NameError: uninitialized constant ForemanRescue::Engine::ForemanOmaha
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_rescue-2.0.0/lib/foreman_rescue/engine.rb:49:in 'block (2 levels) in <class:Engine>'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/exe/rake:27:in '<top (required)>'
`

**Comment by timogoebel** [comment]
@metalcated: Thanks for the report. This was actually fixed in https://github.com/dm-drogeriemarkt/foreman_rescue/commit/5f66e64969129acdd7b0813ccf9cf2f788de6b50.

It looks like the package is missing in the 1.21 + 1.22 repos. I'll see to it that they are added there.

**Comment by timogoebel** [comment]
This issue should be resolved by now.
