### ISSUE TITLE
Undefined method 'rescue mode'

### ISSUE THREAD

**Issue by brendan4linux** [dm-drogeriemarkt/foreman_rescue#24]
Hello - recently i've installed the rescue plugin on our Katello environment from the Foreman repos on CentOS7 and i'm getting an error when activating rescue mode:

undefined method `rescue_mode=' for #<Host::Managed:0x000000001d17fc60> Did you mean? rescue_host_url

Anything I may have missed during the install? Ran 'yum -y install tfm-rubygem-foreman_rescue' followed by 'foreman-rake db:migrate' and 'foreman-rake db:seed'.

[root@katello ~]# rpm -q katello foreman tfm-rubygem-foreman_rescue
katello-3.18.4-1.el7.noarch
foreman-2.3.5-1.el7.noarch
tfm-rubygem-foreman_rescue-3.0.0-1.fm2_1.el7.noarch

Thanks,

**Comment by laugmanuel** [comment]
Hi @brendan4linux,

thank's for opening the issue.
I checked my test environment with the same foreman/katello/plugin version, and for me enabling the rescue mode works.

The steps you listed should be sufficient.
I guess you did also restart the Foreman instance after installing/migrating the DB? 

Can you please run the following two commands and share the output?
```sh
# to see if the migration is applied
foreman-rake db:migrate:status | grep 20170901131321

# to check if rescue_mode can be queried using rails console
echo 'Host::Managed.first.rescue_mode' | foreman-rake console
```

**Comment by brendan4linux** [comment]
Thank you for your quick response! For whatever reason, installing it the second time (and alone / not installing with wreckingball concurrently) seems to have worked! I'm not sure if this output is as expected, but I can click rescue/modify hosts without the error now.  Thanks again -

[root@katello ~]# foreman-rake db:migrate:status | grep 20170901131321
   up     20170901131321  Add rescue mode to hostforeman rescue
[root@katello ~]# echo 'Host::Managed.first.rescue_mode' | foreman-rake console
API controllers newer than Apipie cache! Run apipie:cache rake task to regenerate cache.
Loading production environment (Rails 6.0.3.4)
Switch to inspect mode.
Host::Managed.first.rescue_mode
false

**Comment by laugmanuel** [comment]
Thank you for reporting back.
The output looks good also - this was just to confirm that the migrations ran (`up`) and the rails console can query the rescue mode status for a given host (`false` in this case).
