### ISSUE TITLE
NoMethodError when combined with foreman_cockpit plugin?

### ISSUE THREAD

**Issue by xTrekStorex** [dm-drogeriemarkt/foreman_rescue#4]
I get the following stacktrace when I open a host view. I barely know ruby but from what I understand the inherited method `host_title_actions` doesnt exist which I relate to foreman_cockpit being installed and redeclaring(?) it as `host_title_actions_with_cockpit` and `host_title_actions_without_cockpit` in https://github.com/theforeman/foreman_cockpit/blob/47ddc0cc19e64c1aadc1c8c5da621ca00361b4e1/app/helpers/concerns/foreman_cockpit/hosts_helper_extensions.rb 

![image](https://user-images.githubusercontent.com/3179810/38805417-08fce37a-4176-11e8-950c-b71bb5f73dbb.png)

**Comment by timogoebel** [comment]
@xTrekStorex: What Foreman version are you running? I believe this is actually something that should be fixed over at foreman_cockpit, see https://github.com/theforeman/foreman_cockpit/pull/15.

**Comment by xTrekStorex** [comment]
Ah sry I forgot to mention that. 1.16.1 as of this morning.
upgraded from 1.16.0 incl. a few gem downgrades (sequel & pg) to fix `foreman-rake db:migrate` and fast_gettext to fix passenger looking for 1.5.1 while 1.6.0 was installed (possibly by me running bundle update)

**Comment by timogoebel** [comment]
Ok, this is because of `Module.prepend` conflicting with `alias_method_chain`.

Foreman < 1.17 (& plugins for Foreman y 1.17) should still use `alias_method_chain`. I'll fix this in the `0.1-stable` branch of this plugin.

**Comment by timogoebel** [comment]
@xTrekStorex: The code in #5 should fix this. Do you mind giving this a shot?

**Comment by xTrekStorex** [comment]
Opening the host view works now. Thanks! 
However clicking "Rescue" triggers another error but I think this should go in another issue 

![image](https://user-images.githubusercontent.com/3179810/38859218-d6b2921c-422d-11e8-988f-cd315eb0d414.png)

My hosts are all on VMware compute resources

**Comment by timogoebel** [comment]
@xTrekStorex: Yeah, that doesn't look related. Please attach the complete stack trace, then it should be easy to figure out.
